### ISSUE TITLE
link to historic archive

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/math-comp.github.io#12]
There is a link to the historic archive on the entry page that does not look reachable anymore.

**Comment by gares** [comment]
The archives of releases are now part of the regular MC releases: https://github.com/math-comp/math-comp/releases/tag/archive

The very old svn history is also available, it's a dedicated repo in the MC org: https://github.com/math-comp/mathcomp-history-before-github

**Comment by affeldt-aist** [comment]
Thank you. I will update that as soon as PR #11 is merged or closed (to avoid conflict on automatically generated files, though this is no big deal actually).
