### ISSUE TITLE
link that causes an error

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/math-comp.github.io#27]
When I click on the `Inria-Microsoft Research Joint Center` link on the first page I get [1].
This is a link that we have updated recently. Is there a better one? Or should we get rid of the link?

--
[1]
```
An error occurred during a connection to www.microsoft.com. The OCSP response does not include a status for the certificate being verified.

Error code: MOZILLA_PKIX_ERROR_OCSP_RESPONSE_FOR_CERT_MISSING

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by gares** [comment]
I get the same errors clicking on links return by Google in response to queries about inria and the joint center. But I'm using ffox too

**Comment by CohenCyril** [comment]
For me it works, using google-chrome

**Comment by affeldt-aist** [comment]
lynx, abaco and mothra are fine too :-)

**Comment by gares** [comment]
well, let's consider this a Firefox issue and leave the link there
